app/urls.py
from django.conf.urls import include, url

import app.views

# Examples:
# url(r'^$', 'init.views.home', name='home'),
urlpatterns = [
    url(r'^list', app.views.competition_list,name='competition_list'),
    url(r'^detail/(?P<id>\d+)$', app.views.competition_detail, name='competition_detail'),
    url(r'^submission/(?P<id>\d+)$', app.views.submission, name='submission'),

]

init/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import app.views

# Examples:
# url(r'^$', 'init.views.home', name='home'),
urlpatterns = [
    url(r'^$', app.views.index, name='index'),
    # url(r'^db', app.views.db, name='db'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'logout.html'}),
    url(r'^competition/', include("app.urls",namespace="app")),

]
# url(r'^blog/', include('blog.urls')),


urlpatterns += staticfiles_urlpatterns()

app/models.py
#-*-coding:utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
# Create your models here.

# Competitioのデータベースモデル
class Competition(models.Model):
    SCORING_CHOICES = (
        (u'MSE', u'MSE'),
        (u'RMSE', u'RMSE'),
        (u'Correlation', u'CORRELATION'),
        (u'Accuracy', u'ACCURACY'),
        (u'F1', u'F1'),
        (u'Adjusted Rand Score', u'ADJUSTED RAND SCORE'),

    )

    CONTEST_CHOICES=(
        (u'Regression','regression'),
        (u'Classification', 'classification'),
        (u'Clustering', 'clustering'),
    )

    name = models.CharField("competition name",max_length=255,unique=True)
    description = models.TextField('description', blank=True)
    contest_type = models.CharField("contest type",choices=CONTEST_CHOICES,max_length=20,default="regression")
    scoring = models.CharField("scoring method",choices=SCORING_CHOICES,max_length=20,default="RMSE")
    data_number = models.IntegerField("answer data size")
    answer = models.TextField('answer')
    mid_test_s = models.IntegerField("start index of mid test",default=0)
    mid_test_e = models.IntegerField("end index of mid test",default=0)
    f_test_s = models.IntegerField("start index of final test",default=0)
    f_test_e = models.IntegerField("end index of final test",default=0)
    end_date =  models.DateTimeField()
    max_submission = models.IntegerField("Max submission per day",default=2)


    def __str__(self):
        return self.name


# Submissionのデータモデル
class Submission(models.Model):
    competition_name = models.ForeignKey(Competition,verbose_name="Competition name",related_name="submission")
    user = models.ForeignKey(User)
    mid_result = models.DecimalField("mid result",max_digits=12, decimal_places=6)
    f_result = models.DecimalField("final result",max_digits=12, decimal_places=6)
    submission_date = models.DateTimeField()
    short_comment = models.CharField("Short Comment",max_length=255,blank=True)
    is_expired = models.IntegerField("is_expired",default=0)

    def __str__(self):
        return User.objects.get(id=self.user_id).username

app/views.py
#-*-coding:utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.contrib.auth.models import User
from django.shortcuts import redirect
from app.models import Competition,Submission
from django.shortcuts import get_object_or_404
from app.tools import scoring
import datetime
import pytz

# Create your views here.
def index(request):
    # return HttpResponse('Hello from Python!')
    return render_to_response('index.html')

# Competitionのリストを返す
@login_required
def competition_list(request):
    competitions = Competition.objects.all().order_by("id")
    return render(request,'competition_list.html',{"competitions":competitions})

from django.db.models.aggregates import Max,Min,Avg

# Competitionの結果を返す
@login_required
def competition_detail(request,id):
    competition = get_object_or_404(Competition, pk=id)
    submissions = competition.submission.all()

    # Competitionが終わっているかの判定
    if competition.end_date < datetime.datetime.now(pytz.timezone('Asia/Tokyo')):
        # aggrigate
        if competition.scoring in ["MSE","RMSE"]:
            query = submissions.filter(is_expired=0).values("user_id").annotate(value=Min("f_result"), ).order_by("value")
        else:
            query = submissions.filter(is_expired=0).values("user_id").annotate(value=Max("f_result"), ).order_by("value")
        competition.expired = True
    else:
        if competition.scoring in ["MSE","RMSE"]:
            query = submissions.filter(is_expired=0).values("user_id").annotate(value=Min("mid_result"), ).order_by("value")
        else:
            query = submissions.filter(is_expired=0).values("user_id").annotate(value=Max("mid_result"), ).order_by("value")

    # 集計したデータにuser情報を付与
    for q in query:
        q["user"] = User.objects.get(id=q["user_id"])

    # 自分自身のsubmissionの取得
    submissions_indv = submissions.filter(user=request.user).order_by("submission_date").reverse()

    return render(request, 'competition_detail.html', {"agg":query,
                                                        "submissions": submissions_indv,
                                                       "competition":competition})


# Submissionの送信画面
@login_required
def submission(request,id):
    competition = get_object_or_404(Competition, pk=id)


    if request.method =="POST":
        # 今日のクエリ数と終了時刻から外れているかの確認
        today = datetime.datetime.now(pytz.timezone('Asia/Tokyo'))
        today_query = competition.submission.filter(user=request.user,
                                                    submission_date__year=today.year,
                                                    submission_date__month=today.month,
                                                    submission_date__day=today.day)
        isOk = True
        is_expired = 1
        if competition.end_date > datetime.datetime.now(pytz.timezone('Asia/Tokyo')):
            is_expired = 0
            if len(today_query) >= competition.max_submission:
                isOk = False

        if isOk:
            result = request.POST["result"].rstrip("\n").split("\n")
            if len(result) == competition.data_number:
                # submissionされたデータがすべて数字であるかの確認
                try:
                    map(float,result)
                except:
                    competition.errors = True
                    return render(request, 'submission.html', {"competition": competition})

                # スコアの導出
                mid_score, f_score = scoring(result,competition)
                temp = Submission(user=request.user,
                                  competition_name=competition,
                                  mid_result=mid_score,
                                  f_result=f_score,
                                  submission_date=datetime.datetime.now(),
                                  short_comment=request.POST["short_comment"],
                                  is_expired=is_expired)
                temp.save()


                return redirect("app:competition_detail",id=id)

        competition.errors = True

    return render(request, 'submission.html', {"competition": competition})

app/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>JUDGE SYSTEM</title>
    <!-- BootstrapのCSS読み込み -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <!-- jQuery読み込み -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- BootstrapのJS読み込み -->
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <style type="text/css"><!-- th{text-align: center} --></style>
  </head>
  <body>
<nav class="navbar navbar-default ">
  <div class="container-fluid">
  <!-- ヘッダー部分 ================ -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">JUDGE</a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav_target">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
        <ul class="nav navbar-nav navbar-right">
        <!-- リンクのみ -->
          <li><a href="{% url "app:competition_list" %}">Competition List</a></li>
{#          <li><a href="{% url 'django.contrib.auth.views.logout' %}">Log Out</a></li>#}
             {% if user.is_authenticated %}
             <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">

                <li class="divider"></li>
                <li>
                    <a href="/logout">Logout</a>
                </li>
            </ul>
            </li>
{#            {% else %}#}
{#                 <li><a href="{% url 'django.contrib.auth.views.login' %}">Log in</a></li>#}
            {% endif %}
{#          <li><a href="#"></a></li>#}
      </ul>
  </div>
</nav>
{% block content %}{% endblock %}

</body>
</html>

app/templates/competition_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h2 class="page-header">{{ competition.name }}</h2>
    <h3>Infomation</h3>
    <ul><li>test size: {{ competition.data_number }}</li>
        <li>contest type:  {{ competition.contest_type }}</li>
        <li>scoring:  {{ competition.scoring }}</li>
        <li>end time:  {{ competition.end_date }}</li>
    </ul>
    {% if competition.expired %}
        <a class="btn btn-danger" role="button"><b>EXPIRED</b></a><br>
        <div style="text-align:right;;">
            {#            <h4>EXPIRED</h4>#}
            <a type="button" class="btn btn-lg btn-primary"
            href="{% url "app:submission" id=competition.id %}" >Submission </a>
        </div>
        <hr>
        <h3>Description</h3>
        {{ competition.description|linebreaks|urlize }}
        <br><h3> Final Score</h3>
      <table class="table table-striped table-bordered order">
      <thead>
        <tr>
          <th>user name</th>
            <th>final score</th>
        </tr>
      </thead>
      <tbody>
        {% for sub in agg %}
        <tr>
          <td>{{ sub.user }}</td>
            <td>{{ sub.value }}</td>
        </tr>
        {% endfor %}
      </tbody>
      </table>

    <h3>Your submission</h3>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>user name</th>
            <th>mid score</th>
            <th>final score</th>
            <th>submission date</th>
            <th>comment</th>
        </tr>
      </thead>
      <tbody>
        {% for sub in submissions %}
        <tr>
          <td>{{ sub.user }}</td>
            <td>{{ sub.mid_result }}</td>
            <td>{{ sub.f_result }}</td>
            <td>{{ sub.submission_date }}</td>
            <td>{{ sub.short_comment }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

{#        koko kara #}
    {% else %}
        <div style="text-align:right;;">
        <a type="button" class="btn btn-lg btn-primary"
           href="{% url "app:submission" id=competition.id %}" >Submission </a>
        </div>
         <hr>
               <h3>Description</h3>

                {{ competition.description|linebreaks|urlize }}

      <table class="table table-striped table-bordered order">
        <br><h3>Mid Score</h3>
      <thead>
        <tr>
          <th>user name</th>
            <th>mid score</th>
        </tr>
      </thead>
      <tbody>
        {% for sub in agg %}
        <tr>
          <td>{{ sub.user }}</td>
            <td>{{ sub.value }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
        <br>
    <h3>Your submission</h3>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>user name</th>
            <th>mid score</th>
            <th>submission date</th>
            <th>comment</th>
        </tr>
      </thead>
      <tbody>
        {% for sub in submissions %}
        <tr>
          <td>{{  sub.user }}</td>
            <td>{{ sub.mid_result }}</td>
            <td>{{ sub.submission_date }}</td>
            <td>{{ sub.short_comment }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}


    </div>
    <div class="col-md-2"></div>
  </div>

</div> <!-- /container -->

<script>
    var tables = document.getElementsByClassName("order");
    var table = tables[tables.length - 1];
    var rows = table.rows;
    th = document.createElement('th');
    th.appendChild(document.createTextNode("order"));
    rows[0].insertBefore(th, rows[0].firstChild);

    for(var i = 0, td; i < rows.length -1; i++){
        td = document.createElement('td');
        td.appendChild(document.createTextNode(i + 1));
        rows[i+1].insertBefore(td, rows[i+1].firstChild);
    }
</script>


{% endblock %}

app/templates/competition_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
            <h3 class="page-header">Competition List</h3>
{#    <a href="{% url 'cms:book_add' %}" class="btn btn-default btn-sm">追加</a>#}
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>competition name</th>
            <th>contest type</th>
            <th>scoring</th>
            <th>end date</th>
        </tr>
      </thead>
      <tbody>
        {% for comp in competitions %}
        <tr>
          <td><a href="{% url "app:competition_detail" id=comp.id %}" >{{ comp.name }}</a></td>
            <td>{{ comp.contest_type }}</td>
            <td>{{ comp.scoring }}</td>
            <td>{{ comp.end_date }}</td>
{#            <a href="{% url 'cms:book_mod' book_id=book.id %}" class="btn btn-default btn-sm">修正</a>#}
{#            <a href="{% url 'cms:book_del' book_id=book.id %}" class="btn btn-default btn-sm">削除</a>#}
{#          </td>#}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
    <div class="col-md-2"></div>
  </div>

</div> <!-- /container -->



{% endblock %}

app/templates/db.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="container">


<h2>Page View Report</h2>


<ul>

{% for greeting in greetings %}
    <li>{{ greeting.when }}</li>
{% endfor %}

</ul>

</div>

{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="jumbotron text-center">
  <div class="container">
    <a href="/" class="lang-logo">
      <img src="{% static 'lang-logo.png'%}">
    </a>
    <h1>Data Competition JUDGE System</h1>
    <p>You can easily judge your results.</p>
    <a type="button" class="btn btn-lg btn-default" href="accounts/login"> Log in</a>
    <a type="button" class="btn btn-lg btn-primary" href="competition/list">Compatition List </a>
  </div>
</div>
<div class="container">

{#  <hr>#}
  <div class="row">
{#    <div class="col-md-6">#}
{#        a#}
{##}
{#    </div>#}
{#    <div class="col-md-6">#}
{#        b#}
{#    </div>#}
  </div> <!-- row -->
   <div class="alert alert-info text-center" role="alert">
    If you find any troubles, please be patient.
  </div>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
<div class="row">
<div class="col-md-4">
</div>
<div class="col-md-4">

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}


  <form method="post" action="{% url 'django.contrib.auth.views.login' %}">    {% csrf_token %}
    <h2 class="form-signin-heading">Please sign in</h2>
{#    <label for="user_id" class="sr-only">User ID</label>#}
{#    <input type="type" id="user_id" class="form-control" placeholder="User ID" required autofocus>#}
{#    <label for="inputPassword" class="sr-only">Password</label>#}
{#    <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>#}
      <label for="{{ form.username.id_for_label }}" class="sr-only">{{ form.username.label }}</label>
        {% render_field form.username class="form-control" placeholder=form.username.label %}
      <label for="{{ form.password.id_for_label }}" class="sr-only">{{ form.password.label }}</label>
        {% render_field form.password class="form-control" placeholder=form.password.label %}

    <div class="checkbox">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit" value="login">Sign in</button>
  </form>

</div>
    <div class="col-md-4"></div>

</div>


<input type="hidden" name="next" value="{{ next }}" />{% endblock %}

app/templates/logout.html
{% extends "base.html" %}

{% block title %}ログアウト{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
    <h3 class="page-header">ログアウトしました</h3>
    </div>
    <div class="col-md-2"></div>
  </div>

{% endblock content %}

app/templates/register.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">

  <form method="post" action="{% url 'django.contrib.auth.views.login' %}">{% csrf_token %}

    <h2 class="form-signup-heading">Please sign up</h2>
    <label for="user_id" class="sr-only">User ID</label>
      <input type="text" class="form-control" id="user_id" placeholder="User ID" required autofocus>
      <label for="email" class="sr-only">Email</label>
    <input type="email" class="form-control" id="email" placeholder="Email" required>
    <label for="password"  class="sr-only">Password</label>
    <input type="password" class="form-control" id="password" placeholder="password" required>

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="login">Sign up</button>
  </form>
    </div>
    <div class="col-md-4"></div>

</div> <!-- /container -->

{% endblock %}

app/templates/submission.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h3 class="page-header">Submission: {{ competition.name }}</h3>
        {% if competition.errors %}
          <div class="alert alert-info text-center" role="alert">
            <h4>Something incorrect.</h4>
            1. The number of lines must be {{ competition.data_number }}<br>
            2. The number of submission in a day must be less than or equal to {{ competition.max_submission }}.<br>
            3. All submission characters are a digit or "." or "\n".
          </div>
        {% endif %}
        <form method="post" action="">    {% csrf_token %}
          <label for="result">Your result:</label>
          <textarea class="form-control" rows="10" name="result"></textarea><br>
          <label for="short_comment">Short comment(opt):</label>
          <input class="form-control" name="short_comment"><br>

            <button class="btn btn-lg btn-primary btn-block" type="submit" value="send">Submit</button>
        </form>
    <div class="col-md-2"></div>
  </div>

</div> <!-- /container -->



{% endblock %}